export const contactData=[
    {   
        image:"https://randomuser.me/api/portraits/women/90.jpg",
        contactName:"Mia K",
        addressStreet:"232 Washhington Street",
        ddressSuburb:"Washington",
        ddressCode:"2244",
        homePhone:"0558654554",
        cellPhone:"555-445-44",
        email:"mia@me.com",
    },
    {   
        image:"https://randomuser.me/api/portraits/men/70.jpg",
        contactName:"Ben Lower",
        addressStreet:"2445 Riverdale Street",
        ddressSuburb:"Some Suburb",
        ddressCode:"4576",
        homePhone:"0558654554",
        cellPhone:"c555-445-44",
        email:"benny@ssyh.com",
    },
    {   
        image:"https://randomuser.me/api/portraits/women/60.jpg",
        contactName:"Sofia Nix",
        addressStreet:"5423 Skeet Street",
        ddressSuburb:"Hamster",
        ddressCode:"3368",
        homePhone:"0554382233",
        cellPhone:"55-4443-945",
        email:"sofia@ff.com",
    },
    {   image:"https://randomuser.me/api/portraits/men/89.jpg",
        contactName:"France Stone",
        addressStreet:"556 Winston Street",
        ddressSuburb:"Jersey",
        ddressCode:"514",
        homePhone:"088555443",
        cellPhone:"78-00-774",
        email:"FStone@stoney.com",
    },
    {   
        image:"https://randomuser.me/api/portraits/women/65.jpg",
        contactName:"Clara Kent",
        addressStreet:"5423 Spew Street",
        ddressSuburb:"Rolling",
        ddressCode:"556",
        homePhone:"056635533",
        cellPhone:"838-553-444",
        email:"cKentf@who.com",
    },
]